# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
