# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 16:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_id1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='id1',
        ),
    ]
